version: '2'

services:

    fedora:
        image:
            "firethorn/fedora:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'fedora/24'
        volumes:
            - /tmp/cache:/var/cache

    java:
        image:
            "firethorn/java:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'java/8'
        depends_on:
            - fedora

    builder:
        image:
            "firethorn/builder:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'builder'
        depends_on:
            - java

    tomcat:
        image:
            "firethorn/tomcat:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'tomcat/8'
        depends_on:
            - java

    sql-proxy:
        image:
            "firethorn/sql-proxy:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'sql-proxy'
        depends_on:
            - fedora

    sql-tunnel:
        image:
            "firethorn/sql-tunnel:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'sql-tunnel'
        depends_on:
            - fedora

    postgres:
        image:
           "firethorn/postgres:${buildname}"
        build:
            context: 'postgres/9'
        depends_on:
            - fedora


