version: '2'

services:

    java:
        extends:
            file:
                docker-base.yml
            service:
                java        

    builder:
        image:
            "firethorn/builder:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'builder'
        depends_on:
            - java

