version: '2'

services:

    builder:
        image:
            "firethorn/builder:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'builder'

