version: '2'

services:

    builder:
        image:
            "firethorn/builder:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: 'builder'

