version: '2'

services:

    fedora:
        image:
            "firethorn/fedora:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: 'fedora/24'

    java:
        image:
            "firethorn/java:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: 'java/8'
        depends_on:
            - fedora

