version: '2'

services:

    tomcat:
        image:
            "firethorn/tomcat:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'tomcat/8'

    sql-proxy:
        image:
            "firethorn/sql-proxy:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'sql-proxy'

    sql-tunnel:
        image:
            "firethorn/sql-tunnel:${buildname}"
        labels:
            uk.ac.roe.firethorn.buildname: "${buildname}"
        build:
            context: 'sql-tunnel'

    postgres:
        image:
           "firethorn/postgres:${buildname}"
        build:
            context: 'postgres/9'


