version: '2.1'

volumes:

    #
    # Build settings.
    settings:

    #
    # The source code cache.
    sourcecode:

    #
    # The Maven build cache.
    buildcache:

services:

    builder:
        hostname:
            "builder"
        image:
            "firethorn/builder:latest"
        tty:
            true
        stdin_open:
            true
        read_only:
            false
        volumes:
            - settings:/etc/firethorn
            - sourcecode:/var/local/build
            - buildcache:/var/local/cache
            - /etc/localtime:/etc/localtime:ro
            - ${SSH_AUTH_SOCK}:/tmp/ssh_auth_sock
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            branch: "${branch}"
            SSH_AUTH_SOCK: /tmp/ssh_auth_sock
        command:
            [bash]


