version: '2.1'

services:

    fedora:
        image:
            "firethorn/fedora:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: '../fedora'

    java:
        image:
            "firethorn/java:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: '../java'
        depends_on:
            - fedora

    tomcat:
        image:
            "firethorn/tomcat:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: '../tomcat'
        depends_on:
            - java

    apache:
        image:
            "firethorn/apache:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: '../apache'
        depends_on:
            - fedora

    sql-proxy:
        image:
            "firethorn/sql-proxy:${buildtag}"
        labels:
            uk.ac.roe.firethorn.buildtag: "${buildtag}"
        build:
            context: '../sql-proxy'
        depends_on:
            - fedora

    postgres:
        image:
           "firethorn/postgres:${buildtag}"
        build:
            context: '../postgres'

    tester:
        image:
           "firethorn/tester:${buildtag}"
        build:
            context: '../tester'
        depends_on:
            - fedora

    builder:
        image:
           "firethorn/builder:${buildtag}"
        build:
            context: '../builder'
        depends_on:
            - fedora

